/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include<stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	__asm ("SVC #243");

	//register uint32_t data __asm ("r0");

	uint32_t data;

	__asm volatile ("MOV %0,r0":"=r"(data)::);

	printf("data=%ld",data);
    /* Loop forever */
	for(;;);
}

__attribute__((naked)) void SVC_Handler(void)
{
	//saving stack base via stack value
	__asm("MRS r0,MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBasestackframe)
{
	printf("In SVC Handler\n");

	uint8_t *pReturn_add = (uint8_t*)pBasestackframe[6];

	// to get svc number
	pReturn_add-=2;

	uint8_t SVC_number = *pReturn_add;

	//printf("SVC_number=%d\n",SVC_number);

	// increment r0 by 4 , return to thread mode

	SVC_number+=4;

	pBasestackframe[0] = SVC_number;
	//while(1);
}
