/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define Alias_base 0x22000000
#define Bitband_base 0x20000000
int main(void)
{
	uint8_t *ptr=(uint8_t*)0x20000200;

	//set it 0xFF
	*ptr=0xff;

	//normal method
	*ptr &= ~(1<<7);

	//set it 0xFF
	*ptr=0xff;

	//bit banding method
	uint8_t *alias_address=(uint8_t*)(Alias_base+(32*(0x20000200-Bitband_base))+7*4);

	//Clearing 7th bit of the address 0x20000200
	*alias_address=0;

	/* Loop forever */
	for(;;);
}
