/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define IRQNO_TIMER2 28
#define IRQNO_I2C1 31

uint32_t *pNVIC_IPRBase =(uint32_t*)0xE000E400;
uint32_t *pNVIC_ISERBase =(uint32_t*)0xE000E100;
uint32_t *pNVIC_ISPRBase =(uint32_t*)0xE000E200;

void config_priority_irqs(uint8_t irq_no,uint8_t priority_value)
{
	//find out no of iprx
	uint8_t iprx=irq_no/4;
	uint32_t *ipr=pNVIC_IPRBase+iprx;

	//position in iprx
	uint8_t pos=(irq_no % 4)*8;

	//config priority
	*ipr &= ~(0xFF << pos);//clear
	*ipr |= (priority_value << pos);
}
int main(void)
{
	//configure priority of peripherals
	config_priority_irqs(IRQNO_TIMER2,0x80);

	config_priority_irqs(IRQNO_I2C1,0x70);

	//set interrupt pending bit //usually set by interrupt causing device
	*pNVIC_ISPRBase= (1<<IRQNO_TIMER2);

	//enable interrupts
	*pNVIC_ISERBase=(1<<IRQNO_I2C1);
	*pNVIC_ISERBase=(1<<IRQNO_TIMER2);

    /* Loop forever */
	for(;;);
}
//isrs
void I2C1_EV_IRQHandler(void)
{
	printf("In I2C event handler");
}

void TIM2_IRQHandler(void)
{
	printf("In Timer 2 handler");
	*pNVIC_ISPRBase= (1<<IRQNO_I2C1);
	while(1);
}
